name: Auto-add issues to project (by label)

on:
  issues:
    types: [opened, labeled]

permissions:
  contents: read
  issues: read
  repository-projects: write

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: backlog
          # label-operator: OR   # optional; remove if not needed
